server {
    listen 80;
    server_name default_server;

    root /var/www/site/web;
    include /etc/nginx/common.conf;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    # Block sensitive file types from being served directly.
    location ~* \.(txt|log|yml|twig|engine|inc|info|install|web\.configmake|module|profile|test|po|sh|htaccess|.*sql|theme|tpl(\.php)?|xtmpl)(~|\.sw[op]|\.bak|\.orig|\.save)?$|^(\.(?!well-known).*|Entries.*|Repository|Root|Tag|Template|composer\.(json|lock))$|^#.*#$|\.php(~|\.sw[op]|\.bak|\.orig\.save)$ {
        return 403;
    }

    # Deny scripts inside vendor folder.
    location ~* /(vendor)\/.*\.(txt|xml|md|html|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ {
        return 403;
    }

    # Cache static assets.
    location ~* ^.+\.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|woff2|eot|mp4|ogg|ogv|webm)$ {
      allow all;
      try_files $uri /index.php?$query_string;
      expires 30d;
      access_log off;
      add_header Cache-Control "public";
    }

    location ~ \..*/.*\.php$ {
        return 403;
    }

    location ~ ^/sites/.*/private/ {
        return 403;
    }

    # Block dotfiles (except .well-known).
    location ~ (^|/)\. {
        return 403;
    }

    location / {
        try_files $uri /index.php?$query_string;
    }

    location @rewrite {
        rewrite ^/(.*)$ /index.php?q=$1;
    }

    # Lock PHP execution to /index.php only.
    location ~ \.php {
       location ~ ^/index\.php {
           # Block httpoxy attacks. See https://httpoxy.org/.
           fastcgi_param HTTP_PROXY "";
           fastcgi_split_path_info ^(.+\.php)(/.*)$;
           try_files               $uri =404;

           fastcgi_read_timeout 1205;
           include fastcgi_params;
           fastcgi_param SCRIPT_FILENAME $request_filename;
           fastcgi_param SERVER_PORT $http_x_forwarded_port;

           fastcgi_intercept_errors off;
           fastcgi_buffers 16 16k;
           fastcgi_buffer_size 32k;

           fastcgi_pass stjernekig_php:6000;

           internal;
       }
       return 403;
    }
}
